<?php

/**
 * BaseRegion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $country_id
 * @property string $region_name
 * @property Country $Country
 * @property Doctrine_Collection $City
 * 
 * @method integer             getCountryId()   Returns the current record's "country_id" value
 * @method string              getRegionName()  Returns the current record's "region_name" value
 * @method Country             getCountry()     Returns the current record's "Country" value
 * @method Doctrine_Collection getCity()        Returns the current record's "City" collection
 * @method Region              setCountryId()   Sets the current record's "country_id" value
 * @method Region              setRegionName()  Sets the current record's "region_name" value
 * @method Region              setCountry()     Sets the current record's "Country" value
 * @method Region              setCity()        Sets the current record's "City" collection
 * 
 * @package    mobiads
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('region');
        $this->hasColumn('country_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('region_name', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Country', array(
             'local' => 'country_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('City', array(
             'local' => 'id',
             'foreign' => 'region_id'));
    }
}