<?php

/**
 * BaseOfficeAds
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $office_id
 * @property integer $ad_id
 * @property Office $Office
 * @property Ad $Ad
 * 
 * @method integer   getOfficeId()  Returns the current record's "office_id" value
 * @method integer   getAdId()      Returns the current record's "ad_id" value
 * @method Office    getOffice()    Returns the current record's "Office" value
 * @method Ad        getAd()        Returns the current record's "Ad" value
 * @method OfficeAds setOfficeId()  Sets the current record's "office_id" value
 * @method OfficeAds setAdId()      Sets the current record's "ad_id" value
 * @method OfficeAds setOffice()    Sets the current record's "Office" value
 * @method OfficeAds setAd()        Sets the current record's "Ad" value
 * 
 * @package    mobiads
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOfficeAds extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('office_ads');
        $this->hasColumn('office_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('ad_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Office', array(
             'local' => 'office_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Ad', array(
             'local' => 'ad_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}