<?php

/**
 * BaseLanguage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $language_name
 * @property string $code
 * @property Doctrine_Collection $CompanyDescription
 * @property Doctrine_Collection $CompanyCategoryDescription
 * @property Doctrine_Collection $GeneralCategoryDescription
 * @property Doctrine_Collection $AdDescription
 * 
 * @method string              getLanguageName()               Returns the current record's "language_name" value
 * @method string              getCode()                       Returns the current record's "code" value
 * @method Doctrine_Collection getCompanyDescription()         Returns the current record's "CompanyDescription" collection
 * @method Doctrine_Collection getCompanyCategoryDescription() Returns the current record's "CompanyCategoryDescription" collection
 * @method Doctrine_Collection getGeneralCategoryDescription() Returns the current record's "GeneralCategoryDescription" collection
 * @method Doctrine_Collection getAdDescription()              Returns the current record's "AdDescription" collection
 * @method Language            setLanguageName()               Sets the current record's "language_name" value
 * @method Language            setCode()                       Sets the current record's "code" value
 * @method Language            setCompanyDescription()         Sets the current record's "CompanyDescription" collection
 * @method Language            setCompanyCategoryDescription() Sets the current record's "CompanyCategoryDescription" collection
 * @method Language            setGeneralCategoryDescription() Sets the current record's "GeneralCategoryDescription" collection
 * @method Language            setAdDescription()              Sets the current record's "AdDescription" collection
 * 
 * @package    mobiads
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLanguage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('language');
        $this->hasColumn('language_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('code', 'string', 3, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 3,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CompanyDescription', array(
             'local' => 'id',
             'foreign' => 'language_id'));

        $this->hasMany('CompanyCategoryDescription', array(
             'local' => 'id',
             'foreign' => 'language_id'));

        $this->hasMany('GeneralCategoryDescription', array(
             'local' => 'id',
             'foreign' => 'language_id'));

        $this->hasMany('AdDescription', array(
             'local' => 'id',
             'foreign' => 'language_id'));
    }
}