<?php

/**
 * BaseCity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $city_name
 * @property integer $region_id
 * @property Region $Region
 * @property Doctrine_Collection $Office
 * 
 * @method string              getCityName()  Returns the current record's "city_name" value
 * @method integer             getRegionId()  Returns the current record's "region_id" value
 * @method Region              getRegion()    Returns the current record's "Region" value
 * @method Doctrine_Collection getOffice()    Returns the current record's "Office" collection
 * @method City                setCityName()  Sets the current record's "city_name" value
 * @method City                setRegionId()  Sets the current record's "region_id" value
 * @method City                setRegion()    Sets the current record's "Region" value
 * @method City                setOffice()    Sets the current record's "Office" collection
 * 
 * @package    mobiads
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('city');
        $this->hasColumn('city_name', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));
        $this->hasColumn('region_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Region', array(
             'local' => 'region_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Office', array(
             'local' => 'id',
             'foreign' => 'city_id'));
    }
}