<?php

/**
 * BaseUserBasket
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $general_categ_id
 * @property sfGuardUser $User
 * @property GeneralCategory $GeneralCategory
 * 
 * @method integer         getUserId()           Returns the current record's "user_id" value
 * @method integer         getGeneralCategId()   Returns the current record's "general_categ_id" value
 * @method sfGuardUser     getUser()             Returns the current record's "User" value
 * @method GeneralCategory getGeneralCategory()  Returns the current record's "GeneralCategory" value
 * @method UserBasket      setUserId()           Sets the current record's "user_id" value
 * @method UserBasket      setGeneralCategId()   Sets the current record's "general_categ_id" value
 * @method UserBasket      setUser()             Sets the current record's "User" value
 * @method UserBasket      setGeneralCategory()  Sets the current record's "GeneralCategory" value
 * 
 * @package    mobiads
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserBasket extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_basket');
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('general_categ_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('GeneralCategory', array(
             'local' => 'general_categ_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}