<?php

/**
 * BaseCompany
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $company_cif
 * @property sfGuardUser $User
 * @property Doctrine_Collection $CompanyDescription
 * @property Doctrine_Collection $Office
 * @property Doctrine_Collection $CompanyCategory
 * @property Doctrine_Collection $Ad
 * 
 * @method integer             getUserId()             Returns the current record's "user_id" value
 * @method string              getCompanyCif()         Returns the current record's "company_cif" value
 * @method sfGuardUser         getUser()               Returns the current record's "User" value
 * @method Doctrine_Collection getCompanyDescription() Returns the current record's "CompanyDescription" collection
 * @method Doctrine_Collection getOffice()             Returns the current record's "Office" collection
 * @method Doctrine_Collection getCompanyCategory()    Returns the current record's "CompanyCategory" collection
 * @method Doctrine_Collection getAd()                 Returns the current record's "Ad" collection
 * @method Company             setUserId()             Sets the current record's "user_id" value
 * @method Company             setCompanyCif()         Sets the current record's "company_cif" value
 * @method Company             setUser()               Sets the current record's "User" value
 * @method Company             setCompanyDescription() Sets the current record's "CompanyDescription" collection
 * @method Company             setOffice()             Sets the current record's "Office" collection
 * @method Company             setCompanyCategory()    Sets the current record's "CompanyCategory" collection
 * @method Company             setAd()                 Sets the current record's "Ad" collection
 * 
 * @package    mobiads
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCompany extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('company');
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('company_cif', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('CompanyDescription', array(
             'local' => 'id',
             'foreign' => 'company_id'));

        $this->hasMany('Office', array(
             'local' => 'id',
             'foreign' => 'company_id'));

        $this->hasMany('CompanyCategory', array(
             'local' => 'id',
             'foreign' => 'company_id'));

        $this->hasMany('Ad', array(
             'local' => 'id',
             'foreign' => 'company_id'));
    }
}