<?php

/**
 * BaseAd
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $company_id
 * @property integer $company_categ_id
 * @property string $ad_mobile_image_link
 * @property Company $Company
 * @property CompanyCategory $CompanyCategory
 * @property Doctrine_Collection $AdDescription
 * @property Doctrine_Collection $OfficeAds
 * 
 * @method integer             getCompanyId()            Returns the current record's "company_id" value
 * @method integer             getCompanyCategId()       Returns the current record's "company_categ_id" value
 * @method string              getAdMobileImageLink()    Returns the current record's "ad_mobile_image_link" value
 * @method Company             getCompany()              Returns the current record's "Company" value
 * @method CompanyCategory     getCompanyCategory()      Returns the current record's "CompanyCategory" value
 * @method Doctrine_Collection getAdDescription()        Returns the current record's "AdDescription" collection
 * @method Doctrine_Collection getOfficeAds()            Returns the current record's "OfficeAds" collection
 * @method Ad                  setCompanyId()            Sets the current record's "company_id" value
 * @method Ad                  setCompanyCategId()       Sets the current record's "company_categ_id" value
 * @method Ad                  setAdMobileImageLink()    Sets the current record's "ad_mobile_image_link" value
 * @method Ad                  setCompany()              Sets the current record's "Company" value
 * @method Ad                  setCompanyCategory()      Sets the current record's "CompanyCategory" value
 * @method Ad                  setAdDescription()        Sets the current record's "AdDescription" collection
 * @method Ad                  setOfficeAds()            Sets the current record's "OfficeAds" collection
 * 
 * @package    mobiads
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAd extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad');
        $this->hasColumn('company_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('company_categ_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ad_mobile_image_link', 'string', 3000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 3000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Company', array(
             'local' => 'company_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('CompanyCategory', array(
             'local' => 'company_categ_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('AdDescription', array(
             'local' => 'id',
             'foreign' => 'ad_id'));

        $this->hasMany('OfficeAds', array(
             'local' => 'id',
             'foreign' => 'ad_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}