<?php

/**
 * BaseCompanyDescription
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $company_id
 * @property integer $language_id
 * @property string $company_name
 * @property Company $Company
 * @property Language $Language
 * 
 * @method integer            getCompanyId()    Returns the current record's "company_id" value
 * @method integer            getLanguageId()   Returns the current record's "language_id" value
 * @method string             getCompanyName()  Returns the current record's "company_name" value
 * @method Company            getCompany()      Returns the current record's "Company" value
 * @method Language           getLanguage()     Returns the current record's "Language" value
 * @method CompanyDescription setCompanyId()    Sets the current record's "company_id" value
 * @method CompanyDescription setLanguageId()   Sets the current record's "language_id" value
 * @method CompanyDescription setCompanyName()  Sets the current record's "company_name" value
 * @method CompanyDescription setCompany()      Sets the current record's "Company" value
 * @method CompanyDescription setLanguage()     Sets the current record's "Language" value
 * 
 * @package    mobiads
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCompanyDescription extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('company_description');
        $this->hasColumn('company_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('language_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('company_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Company', array(
             'local' => 'company_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Language', array(
             'local' => 'language_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}