<?php

/**
 * BaseCompanyCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $company_id
 * @property integer $general_categ_id
 * @property Company $Company
 * @property GeneralCategory $GeneralCategory
 * @property Doctrine_Collection $CompanyCategoryDescription
 * @property Doctrine_Collection $Ad
 * 
 * @method integer             getCompanyId()                  Returns the current record's "company_id" value
 * @method integer             getGeneralCategId()             Returns the current record's "general_categ_id" value
 * @method Company             getCompany()                    Returns the current record's "Company" value
 * @method GeneralCategory     getGeneralCategory()            Returns the current record's "GeneralCategory" value
 * @method Doctrine_Collection getCompanyCategoryDescription() Returns the current record's "CompanyCategoryDescription" collection
 * @method Doctrine_Collection getAd()                         Returns the current record's "Ad" collection
 * @method CompanyCategory     setCompanyId()                  Sets the current record's "company_id" value
 * @method CompanyCategory     setGeneralCategId()             Sets the current record's "general_categ_id" value
 * @method CompanyCategory     setCompany()                    Sets the current record's "Company" value
 * @method CompanyCategory     setGeneralCategory()            Sets the current record's "GeneralCategory" value
 * @method CompanyCategory     setCompanyCategoryDescription() Sets the current record's "CompanyCategoryDescription" collection
 * @method CompanyCategory     setAd()                         Sets the current record's "Ad" collection
 * 
 * @package    mobiads
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCompanyCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('company_category');
        $this->hasColumn('company_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('general_categ_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Company', array(
             'local' => 'company_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('GeneralCategory', array(
             'local' => 'general_categ_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('CompanyCategoryDescription', array(
             'local' => 'id',
             'foreign' => 'company_categ_id'));

        $this->hasMany('Ad', array(
             'local' => 'id',
             'foreign' => 'company_categ_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => true,
             'rootColumnName' => 'root_id',
             ));
        $this->actAs($timestampable0);
        $this->actAs($nestedset0);
    }
}