<?php

/**
 * BaseCompanyCategoryDescription
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $language_id
 * @property integer $company_categ_id
 * @property string $company_categ_name
 * @property text $company_categ_description
 * @property Language $Language
 * @property CompanyCategory $CompanyCategory
 * 
 * @method integer                    getLanguageId()                Returns the current record's "language_id" value
 * @method integer                    getCompanyCategId()            Returns the current record's "company_categ_id" value
 * @method string                     getCompanyCategName()          Returns the current record's "company_categ_name" value
 * @method text                       getCompanyCategDescription()   Returns the current record's "company_categ_description" value
 * @method Language                   getLanguage()                  Returns the current record's "Language" value
 * @method CompanyCategory            getCompanyCategory()           Returns the current record's "CompanyCategory" value
 * @method CompanyCategoryDescription setLanguageId()                Sets the current record's "language_id" value
 * @method CompanyCategoryDescription setCompanyCategId()            Sets the current record's "company_categ_id" value
 * @method CompanyCategoryDescription setCompanyCategName()          Sets the current record's "company_categ_name" value
 * @method CompanyCategoryDescription setCompanyCategDescription()   Sets the current record's "company_categ_description" value
 * @method CompanyCategoryDescription setLanguage()                  Sets the current record's "Language" value
 * @method CompanyCategoryDescription setCompanyCategory()           Sets the current record's "CompanyCategory" value
 * 
 * @package    mobiads
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCompanyCategoryDescription extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('company_category_description');
        $this->hasColumn('language_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('company_categ_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('company_categ_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('company_categ_description', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Language', array(
             'local' => 'language_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('CompanyCategory', array(
             'local' => 'company_categ_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}