<?php

/**
 * BaseGeneralCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $CompanyCategory
 * @property Doctrine_Collection $GeneralCategoryDescription
 * @property Doctrine_Collection $UserBasket
 * 
 * @method Doctrine_Collection getCompanyCategory()            Returns the current record's "CompanyCategory" collection
 * @method Doctrine_Collection getGeneralCategoryDescription() Returns the current record's "GeneralCategoryDescription" collection
 * @method Doctrine_Collection getUserBasket()                 Returns the current record's "UserBasket" collection
 * @method GeneralCategory     setCompanyCategory()            Sets the current record's "CompanyCategory" collection
 * @method GeneralCategory     setGeneralCategoryDescription() Sets the current record's "GeneralCategoryDescription" collection
 * @method GeneralCategory     setUserBasket()                 Sets the current record's "UserBasket" collection
 * 
 * @package    mobiads
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGeneralCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('general_category');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CompanyCategory', array(
             'local' => 'id',
             'foreign' => 'general_categ_id'));

        $this->hasMany('GeneralCategoryDescription', array(
             'local' => 'id',
             'foreign' => 'general_categ_id'));

        $this->hasMany('UserBasket', array(
             'local' => 'id',
             'foreign' => 'general_categ_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => true,
             'rootColumnName' => 'root_id',
             ));
        $this->actAs($timestampable0);
        $this->actAs($nestedset0);
    }
}