<?php

/**
 * BaseGeneralCategoryDescription
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $language_id
 * @property integer $general_categ_id
 * @property string $general_categ_name
 * @property text $general_categ_description
 * @property Language $Language
 * @property GeneralCategory $GeneralCategory
 * 
 * @method integer                    getLanguageId()                Returns the current record's "language_id" value
 * @method integer                    getGeneralCategId()            Returns the current record's "general_categ_id" value
 * @method string                     getGeneralCategName()          Returns the current record's "general_categ_name" value
 * @method text                       getGeneralCategDescription()   Returns the current record's "general_categ_description" value
 * @method Language                   getLanguage()                  Returns the current record's "Language" value
 * @method GeneralCategory            getGeneralCategory()           Returns the current record's "GeneralCategory" value
 * @method GeneralCategoryDescription setLanguageId()                Sets the current record's "language_id" value
 * @method GeneralCategoryDescription setGeneralCategId()            Sets the current record's "general_categ_id" value
 * @method GeneralCategoryDescription setGeneralCategName()          Sets the current record's "general_categ_name" value
 * @method GeneralCategoryDescription setGeneralCategDescription()   Sets the current record's "general_categ_description" value
 * @method GeneralCategoryDescription setLanguage()                  Sets the current record's "Language" value
 * @method GeneralCategoryDescription setGeneralCategory()           Sets the current record's "GeneralCategory" value
 * 
 * @package    mobiads
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGeneralCategoryDescription extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('general_category_description');
        $this->hasColumn('language_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('general_categ_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('general_categ_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('general_categ_description', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Language', array(
             'local' => 'language_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('GeneralCategory', array(
             'local' => 'general_categ_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}