<?php

/**
 * BaseAdDescription
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $language_id
 * @property integer $ad_id
 * @property string $ad_name
 * @property text $ad_description
 * @property string $ad_mobile_text
 * @property string $ad_link
 * @property Language $Language
 * @property Ad $Ad
 * 
 * @method integer       getLanguageId()     Returns the current record's "language_id" value
 * @method integer       getAdId()           Returns the current record's "ad_id" value
 * @method string        getAdName()         Returns the current record's "ad_name" value
 * @method text          getAdDescription()  Returns the current record's "ad_description" value
 * @method string        getAdMobileText()   Returns the current record's "ad_mobile_text" value
 * @method string        getAdLink()         Returns the current record's "ad_link" value
 * @method Language      getLanguage()       Returns the current record's "Language" value
 * @method Ad            getAd()             Returns the current record's "Ad" value
 * @method AdDescription setLanguageId()     Sets the current record's "language_id" value
 * @method AdDescription setAdId()           Sets the current record's "ad_id" value
 * @method AdDescription setAdName()         Sets the current record's "ad_name" value
 * @method AdDescription setAdDescription()  Sets the current record's "ad_description" value
 * @method AdDescription setAdMobileText()   Sets the current record's "ad_mobile_text" value
 * @method AdDescription setAdLink()         Sets the current record's "ad_link" value
 * @method AdDescription setLanguage()       Sets the current record's "Language" value
 * @method AdDescription setAd()             Sets the current record's "Ad" value
 * 
 * @package    mobiads
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdDescription extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_description');
        $this->hasColumn('language_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ad_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ad_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('ad_description', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('ad_mobile_text', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 500,
             ));
        $this->hasColumn('ad_link', 'string', 3000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 3000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Language', array(
             'local' => 'language_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Ad', array(
             'local' => 'ad_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}