<?php

/**
 * AdDescriptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdDescriptionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdDescriptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdDescription');
    }
}