<?php

/**
 * AdDescriptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdDescriptionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdDescriptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdDescription');
    }


   /**
    * Returns ads with ad descriptions by company and language id.
    *
    * @return related ad to a company and language id as Doctrine Query
    */
    public function getAdsByCompanyandLanguageIdQuery($companyId, $languageId)
    {
        return $this->createQuery('addescription')->where('ad.company_id = ?', $companyId)
                                                  ->andWhere('addescription.language_id = ?', $languageId)
                                                  ->innerjoin('addescription.Ad ad')
                                                  ->orderBy('ad.id');
    }

}
