<?php

/**
 * AdTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ad');
    }


   /**
    * Returns ads by company id.
    *
    * @return related ads to a company id as Doctrine Query
    */
    public function getAdsByCompanyIdQuery($companyId)
    {
        return $this->createQuery('ad')->where('ad.company_id = ?', $companyId);
    }
}
