<?php

/**
 * CityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('City');
    }


   /**
    * Returns a query which is able to recover the city_name field of a City Table
    *
    * @return object Doctrine_Query
    */
    public function getCityNameQuery()
    {
        $query = $this->createQuery('city')
                        ->select('city.city_name');

        return $query;
    }

    public function getCitiesByRegionIdQuery($regionId)
    {
        return $this->createQuery('city')->where('city.region_id = ?', $regionId);
    }
}
