<?php

/**
 * Company
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mobiads
 * @subpackage model
 * @author     Gustavo Martin Morcuende
 * @version
 */
class Company extends BaseCompany
{

 /**
  * Returns the string representation of this object.
  *
  * @return string
  */
  public function __toString()
  {
    $languageId = sfContext::getInstance()->getUser()->getGuardUser()->getLanguage()->getId();

    //Check if there is description with the user's language
    $companyDescriptions = CompanyDescriptionTable::getInstance()->findByCompanyId($this->getId());
    foreach ($companyDescriptions as $companyDescription)
    {
        if ($companyDescription->getLanguageId() == $languageId)
        {
           //We found it!!!
           return (string) $companyDescription->getCompanyName();
        }
    }

    //Otherwise return with the default language
    $languageCode = sfConfig::get('app_default_language');
    $languageId = LanguageTable::getInstance()->findOneByCode($languageCode)->getId();
    foreach ($companyDescriptions as $companyDescription)
    {
        if ($companyDescription->getLanguageId() == $languageId)
        {
           //We found the default name description!!!
           return (string) $companyDescription->getCompanyName();
        }
    }

    //Finally, if nothing was found, return nice error message.
    return (string) "Company without default language";
  }
}
