<?php

/**
 * CompanyCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompanyCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompanyCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CompanyCategory');
    }


   /**
    * Returns company categories by company id.
    *
    * @return related company categories to a company as Doctrine Query
    */
    public function getCompanyCategoriesByCompanyIdQuery($companyId, $currentCategory = null, $currentLft = null, $currentRgt = null)
    {
        if ($currentCategory != null)
        {
            return $this->createQuery('cc')->where('cc.level = ?', '0')
                                           ->orWhere('cc.company_id = ?', $companyId)
                                           ->andWhere('cc.lft > ? or cc.lft < ?', array($currentRgt, $currentLft))
                                           ->orderBy('cc.lft');
        }
        else
        {
            return $this->createQuery('cc')->where('cc.company_id = ?', $companyId)
                                           ->orWhere('cc.level = ?', '0')
                                           ->orderBy('cc.lft');
        }
    }


   /**
    * Returns company categories by company id skipping the main category called Producto.
    *
    * @return related company categories to a company as Doctrine Query
    */
    public function getCompanyCategoriesByCompanyIdQuerySkipMain($companyId)
    {
        return $this->createQuery('cc')->where('cc.company_id = ?', $companyId)
                                       ->andWhere('cc.level != ?', '0')
                                       ->orderBy('cc.lft');
    }
}
