<?php

/**
 * CompanyCategoryDescriptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompanyCategoryDescriptionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompanyCategoryDescriptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CompanyCategoryDescription');
    }
}
