<?php

/**
 * CompanyCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompanyCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompanyCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CompanyCategory');
    }


   /**
    * Returns company categories by company id.
    *
    * @return related company categories to a company as Doctrine Query
    */
    public function getCompanyCategoriesByCompanyIdQuery($companyId, $currentCategory = null)
    {
        if ($currentCategory != null)
        {
            return $this->createQuery('cc')->where('cc.company_id = ?', $companyId)
                                           ->andWhere('cc.id != ?', $currentCategory)
                                           ->orWhere('cc.id = ?', '1')
                                           ->orderBy('cc.lft');
        }
        else
        {
            return $this->createQuery('cc')->where('cc.company_id = ?', $companyId)
                                           ->orWhere('cc.id = ?', '1')
                                           ->orderBy('cc.lft');
        }
    }
}
