<?php

/**
 * CompanyDescriptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompanyDescriptionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompanyDescriptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CompanyDescription');
    }
}