<?php

/**
 * CompanyCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mobiads
 * @subpackage model
 * @author     Gustavo Martin Morcuende
 * @version
 */
class CompanyCategory extends BaseCompanyCategory
{
  /**
   * Returns the string representation of this object.
   *
   * @return string
   */
  public function __toString()
  {
    $languageId = sfContext::getInstance()->getUser()->getGuardUser()->getLanguage()->getId();

    //Check if there is description with the user's language
    $categoryDescriptions = CompanyCategoryDescriptionTable::getInstance()->findByCompanyCategId($this->getId());
    foreach ($categoryDescriptions as $categoryDescription)
    {
        if ($categoryDescription->getLanguageId() == $languageId)
        {
           //We found it!!!
           return (string) $categoryDescription->getCompanyCategName();
        }
    }

    //Otherwise return with the default language
    $languageCode = sfConfig::get('app_default_language');
    $languageId = LanguageTable::getInstance()->findByCode($languageCode);
    foreach ($categoryDescriptions as $categoryDescription)
    {
        if ($categoryDescription->getLanguageId() == $languageId)
        {
           //We found the default name description!!!
           return (string) $categoryDescription->getCompanyCategName();
        }
    }

    //Finally, if nothing was found, return nice error message.
    return (string) "Company category without default language";
  }
}
