<?php

/**
 * CompanyCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mobiads
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CompanyCategory extends BaseCompanyCategory
{
 /**
  * Returns the string representation of this object.
  *
  * @return string
  */
  public function __toString()
  { 
    return (string) $this->getCompanyCategName();
  }

}
