<?php

/**
 * GeneralCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GeneralCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GeneralCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GeneralCategory');
    }
}