<?php

/**
 * GeneralCategoryDescriptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GeneralCategoryDescriptionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GeneralCategoryDescriptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GeneralCategoryDescription');
    }
}