<?php

/**
 * Language
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mobiads
 * @subpackage model
 * @author     Gustavo Martin Morcuende
 * @version
 */
class Language extends BaseLanguage
{

  /**
   * Returns the string representation of this object.
   *
   * @return string
   */
   public function __toString()
   {
      return (string) $this->getLanguageName();
   }
}
