<?php

/**
 * OfficeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OfficeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OfficeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Office');
    }


   /**
    * Returns offices by company id with sort
    *
    * @return related offices to a company id.
    * TODO: order by longitude and latitude
    */
    public function getOfficesByCompanyIdWithSortQuery($companyId, $sort)
    {
         return $this->createQuery('office')->where('office.company_id = ?', $companyId)
                                            ->innerjoin('office.City city')
                                            ->innerjoin('city.Region region')
                                            ->innerjoin('region.Country country')
                                            ->orderBy($sort);
    }
}

