<?php

/**
 * OfficeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OfficeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OfficeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Office');
    }


   /**
    * Returns offices by company id.
    *
    * @return related offices to a company id.
    */
    public function getOfficesByCompanyIdQuery($companyId)
    {
         return $this->createQuery('office')->where('office.company_id = ?', $companyId)
                                            ->orderBy('office.id');
    }
}

