<?php

/**
 * OfficeAdsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OfficeAdsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OfficeAdsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OfficeAds');
    }
}