<?php

/**
 * Office
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mobiads
 * @subpackage model
 * @author     Gustavo Martin Morcuende
 * @version
 */
class Office extends BaseOffice
{
    public function getGpsST_AsText()
    {
        $aux=$this->getOfficeGps();
        if ($aux)
        {
            //Using a PostGIS query to convert a GIS value? This is a bit strange
            $results=Doctrine_Manager::getInstance()->getCurrentConnection()->fetchColumn("SELECT ST_AsText('$aux')");
            return trim($results['0'], "POINT()");
        }
        else
            return 0;
    }

    public function getLongitude()
    {
        $gpsST_AsText=$this->getGpsST_AsText();

        $longitude = strstr($gpsST_AsText, ' ', true);

        return $longitude;
    }

    public function getLatitude()
    {
        $gpsST_AsText=$this->getGpsST_AsText();

        $latitude = strstr($gpsST_AsText, ' ');

        return $latitude;
    }

}
