<?php

/**
 * RegionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RegionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RegionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Region');
    }

   /**
    * Returns a query which is able to retrieve regions related to a specified country.
    *
    * @return object Doctrine_Query
    */
    public function getRegionsByCountryIdQuery($countryId)
    {
        return $this->createQuery('region')->where('region.country_id = ?', $countryId);
    }
}
