<?php

/**
 * UserBasketTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserBasketTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserBasketTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserBasket');
    }
}