<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/05/10 21:24:27

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=mobileadvertising',
  'username' => 'postgres',
  'password' => NULL,
  'name' => 'doctrine',
)),);
