# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  max_offices_on_pager:      3
  max_ads_on_pager:          2
  max_categories_on_pager:   3
  default_picture_directory: /home/gustavo/symfonyreloaded/mobiads/web/uploads/images/
  default_language:          spa                      # Everything must exist at least with this language
  default_country:           Spain

  sf_guard_plugin:
     remember_key_expiration_age: 2592000             # 30 days in seconds
     remember_cookie_name:        mobicomRemember     # used by sfGuardSecurityUser.class.php
     success_signin_url:          @homepage           # the plugin uses the referer as default
     success_signout_url:         @sf_guard_signin    # used by BasesfGuardAuthActions.class.php. After logout we are redirected to this page
     signin_url_path:             login               # used by sfGuardRememberMeFilter.class.php. The Remember cookie must not be used when using the login page
     remember_cookie_path:        /companyfront.php   # used by sfGuardSecurityUser.class.php. The scope of the Remeber cookie
     remember_cookie_domain:      .localhost

  recaptcha:
     private_key: 6Lcg9dESAAAAACrrfQ5l9OLp3nq93lN1ra1q-8Kn
     public_key:  6Lcg9dESAAAAAG-QQLfE8By9c8ufO8WjuhBMz2-M
